name: First Workflow
on: workflow_dispatch # can manually trigger workflow with this
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Print Greeting
        run: echo "Hello World!"
      - name: Print Goodbye
        run: echo "Goodbye!"

